# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'onLineDB' do
pod 'LGSideMenuController', '~> 1.0.0'
pod 'AFNetworking', "~> 2.0"
#pod 'RestKit', "~> 0.25"
end

target 'onLineDBTests' do

end

target 'onLineDBUITests' do

end

